# Generated by Django 5.1 on 2024-08-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('descriptions', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'настройка баннера',
            },
        ),
    ]
