# Generated by Django 5.1 on 2024-08-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='icon',
            field=models.CharField(choices=[('СЕТЬ.', 'СЕТЬ.'), ('АНАЛИТИКА.', 'АНАЛИТИКА.'), ('Развитие.', 'Развитие.')], default=1, max_length=10, verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
